### ISSUE TITLE
Nullexception when acquiring higher skillls in Tool Smithing

### ISSUE THREAD

**Issue by japalo** [mdf25/FennecMod#1]
While playing as a miner with Miner Mastery 1 and trying to apply a higher level of tool smithing, the skills menu crashes when trying to open the skill menu.

The console opens with a null exception. We deleted my character multiple times in order to figure the bug out, and we got to the conclusion that after adding skill points to tool smithing (i think it was the 7th skill point) the skill menu crashed.

I tried to post in the forums, but wasn't allowed to. Hope this ticket reaches you :)

Have a great one!

**Comment by mdf25** [comment]
Greetings :D This has been fixed in 1.0-Stable branch - I'll be pushing this soon. Double checking the mod launcher as well to make sure we're in sync there but hopefully it's all good :)

**Comment by japalo** [comment]
Updated my local copy. Should we also update our dedicated server? I still have the same problem. :(

**Comment by japalo** [comment]
Updated the server as well, still same problem :/

**Comment by mdf25** [comment]
Did you definitely get the 1.0 branch from the mod launcher and copy those files over or did you download directly from the repo here? I've had others report all is good on the server side of things. I think you may have downloaded the master branch which hasn't had the 1.0 changes pushed to that yet (the master branch is DevBranch on the launcher). If you're still having issues I'll double check :)

If you want to apply the fix directly yourself on the server, it's actually a simple one. Open up the Config folder and open progression.xml, and do a search for "MimerMastery" and change it to "MinerMastery" which was the typo causing the nullref :)

**Comment by japalo** [comment]
We used the mod launcher so I guess that's why it didn't work for us. I'll just wait for the next update in the mod launcher :)
